### ISSUE TITLE
Calling transformation multiple times with different options

### ISSUE THREAD

**Issue by uhinze** [mastersign/gulp-text-simple#2]
This is more of a documentation improvement proposal I think:

I was following the documentation for usage with options: 
```
// create the Gulp transformation factory with GulpText simple
var myTransformation = textTransformation(transformString);

gulp.task('default', function () {
    return gulp.src('src/*.txt')
        .pipe(myTransformation({ mode: 'upper' })) // create the transformation with options
        .pipe(gulp.dest('out/'));
});
```
Then I used the same transformation (myTransformation) with different options (without waiting for the first to finish, because they are independent). But myTransformation will of course be overridden, resulting in the issue that only the option that is used last will actually be used (multiple times).

I fixed this by modifying it like this:
```
gulp.task('default', function () {
    return gulp.src('src/*.txt')
        .pipe(textTransformation(transformString)({ mode: 'upper' })) // create the transformation with options
        .pipe(gulp.dest('out/'));
});
```

Should this enter the documentation somehow?

**Comment by mastersign** [comment]
Thanks for pointing that out. This behavior is not intended.
